spring.datasource.url=jdbc:mysql://TU_IP_VPS:3306/bd_buenaventura?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=erp_user
spring.datasource.password=teo120044
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver