spring.application.name=erp
spring.profiles.active=local

server.port=8080

jwt.secret=MiClaveSuperSeguraJwtParaErp2026MiClaveSuperSeguraJwt
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl